name: Check
on: push

jobs:

  fir_job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install
      
      - name: Lint
        run: npm run lint

  sec_job:
    needs: [fir_job]
    strategy: #Конструкция strategy.matrix нужна чтобы применить один job с разными параметрами
      matrix:
        version: [14,16,18]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.version}}

      - name: Install postgresql
        run: sudo apt-get install -y postgresql
      
      - name: Watch postgres version
        run: psql --version