name: Check
on: push

jobs:
 fir_job:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install apache2
      run: sudo apt-get install -y apache2

    - name: Watch apache2 version
      run: apache2 -v

 sec_job:
  needs: [fir_job]
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4

   - name: Install postgresql
     run: sudo apt-get install -y postgresql

   - name: Watch postgres version
     run: psql --version
  
 secret:
  runs-on: ubuntu-latest

  steps:
   - name: Print secret
     run: echo ${{ secrets.TEST }}
