name: Check
on: push

jobs:

  fir_job:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get install apache2
      
      - name: Watch apache2 version
        run: apache2 -v

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt-get install postgres
      
      - name: Watch postgres version
        run: postgres --version