name: My-GitHub
env:
 APPLICATION_NAME: "MyFlask"
 DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"
 
on:
 push:
  branches:
   - main

jobs: 
 my_testing:
  runs-on: ubuntu-latest

  steps:
  - name: Print Hello Message
    run: echo "Hello World from Testing"
  - name: Execure few commands
    run: |
      echo "Hello Message1"
      echo "Hello Message2"
      echo "Application name: ${{env.APPLICATION_NAME}}"


  - name: Git clone my repo
    uses: actions/checkout@v1
    
  - name: List current folder
    run: ls -la

 my_deploy:
  runs-on: ubuntu-latest
  needs: [my_testing]
  env:
   VAR1: "this is job level variable1"
   VAR2: "this is job level variable2"
  steps:
  - name: Print Hello Message
    run: echo "Hello World from Deploy"  
    
  - name: Print env vars
    run: |
      echo "VAR1=${{env.VAR1}}"
      echo "VAR2=${{env.VAR2}}"
      echo "VAR3=$LOCAL_VAR
    env:
     LOCAL_VAR: "THIS is local super var"
    
  - name: Deployment Package
    run: echo "Application name:${{env.DEPLOY_PACKAGE_NAME}}"

  - name: Lets test some packages iof the are here
    run: aws --version

  - name: Lets test some packages iof the are here 2
    run: zip
